### ISSUE TITLE
Find a better way to query the pages

### ISSUE THREAD

**Issue by eddysims** [morganhvidt/find-my-blocks#36]
Based on this Twitter thread

https://twitter.com/jasonbahl/status/1257479713259311104

**Comment by jasonbahl** [comment]
@eddysims one thought (haven't put a TON of thought into it) would be to register a custom taxonomy, let's say "used_blocks" for example. 

And when a Post that is using Gutenberg is saved, you could parse the blocks at that point, and store a relationship from that Post to terms in the "used_blocks" Taxonomy named after the blocks. 

Then, you could do a Tax query to more efficiently find out how many posts are using certain blocks. 

You could even display the used blocks in a UI so folks could filter their Posts by certain blocks in use in the Posts table? 🤔 

I'm sure there are tradeoffs to this approach too, but it feels more efficient overall and could open up some really cool possibilities. 

Folks could even do stuff like hit the REST API and (pseudo) get a list of Posts using a specific block, like so: `/posts/?used_blocks="core/paragraph"`

**Comment by eddysims** [comment]
@jasonbahl interesting idea. I wonder if this could populate posts that have been using gutenberg that haven't been saved. 

Maybe with this approach there could also be some sort of "sync" action that could run through `x` number of pages at a time and populate that list. Will let this marinate in my head for a little bit

**Comment by jasonbahl** [comment]
@eddysims ya, I think some sort of initial crawl (using paginated fetching) would work. 

You could fetch 100 posts per page, analyze their content, save the terms, then fetch the next 100 until you have no more to fetch. 

This kind of paginated fetching will ensure you're not causing resource issues on the users server.

**Comment by eddysims** [comment]
The more I think about this, the more I like it. I was wondering the next direction for this plugin and I think this is it! 

@jasonbahl when I start looking into this, would you mind putting some 👀 on the PR?

**Comment by 0aveRyan** [comment]
In some ways very similar to how `Regenerate Thumbnails` works with a REST Endpoint using pagination. 

https://plugins.trac.wordpress.org/browser/regenerate-thumbnails/trunk/includes/class-regeneratethumbnails-regenerator.php#L447

Another idea that wouldn't require the overhead of a taxonomy may be just doing paginated batching, storing the results in an option with a timestamp and hash, and simply showing to users the scan results with a timestamp. The taxonomy would make re-scanning more efficient for large sites, but also burns a bunch of extra taxonomy data into the database.

Pros and cons of both approaches 🤷‍♂️  Really depends on how often someone needs to scan content.

**Comment by eddysims** [comment]
Going to close 

> I'm of course not sure wether there is anything you can really easily do about this, but maybe with pagination processing them in chunks rather than all at once might be a cool idea.
> 
> When I change:
> 
> ```
> $posts = get_posts(
> 	array(
> 		'posts_per_page' => -1,
> 		'post_type'      => $post_type,
> 	)
> );
> ```
> 
> to
> 
> ```
> $posts = get_posts(
> 	array(
> 		'posts_per_page' => 100,
> 		'post_type'      => $post_type,
> 	)
> );
> ```
> 
> in `inc/register_route.php` it works.
> 
> And maybe having an error handler that tells you when the request didn't work might be a nice addition :) Currently the block rotation animation just keeps spinning endlessly

**Comment by morganhvidt** [comment]
✅ Batch loading has been added to v4 with performance settings for users to choose how many posts to fetch at a time.
