### ISSUE TITLE
Use theme color instead of brand color

### ISSUE THREAD

**Issue by eddysims** [morganhvidt/find-my-blocks#38]
Lets try changing the color scheme from the brand colors, to the users theme colors.

**Comment by eddysims** [comment]
I have tried making some small changes to make the color scheme more "WordPress" and I didn't like it. I tried using the current theme color, as well as using the WordPress blue for the active menu items. 


I think to make this work would require deeper design thinking. Pushing to low priority for now.

**Comment by morganhvidt** [comment]
Done in v4!
