### ISSUE TITLE
Switch for Reusable Blocks Admin menu entry

### ISSUE THREAD

**Issue by johnfleming** [morganhvidt/find-my-blocks#45]
Would be good to enable this as a feature that can be turned on and off like showing core blocks.   There are a couple of other plugins that have a richer where used feature set for  reusable blocks and this creates duplicate admin entries and the one from FMB is not displayed.

**Comment by eddysims** [comment]
@johnfleming this shouldn't be to difficult to do.

**Comment by johnfleming** [comment]
Thanks Eddy.  Plugin has been a great addition to our Block Editor workflow.

**Comment by morganhvidt** [comment]
V4 will include a "Quick link" to the Reusable Blocks admin menu instead. We'll leave WordPress to handle the UI for their block menus.
