### ISSUE TITLE
Why are you off wordpress.org?

### ISSUE THREAD

**Issue by benupham** [morganhvidt/find-my-blocks#93]
Hi, 

Very useful plugin, thanks for building it. Can you tell me why it is off WP.org? It looks like there's a possible security hole you need to patch? 

Ben

**Comment by ajitbohra** [comment]
https://wordpress.org/support/topic/find-my-blocks-not-available/#post-14836904

> Hi all and to everyone who sees this.
Yes, WP messaged me and let me know that there are some security concerns with the plugin. I addressed the original issue and now I have been given a few more things that need to be addressed.
I will be trying my best to get the plugin back online as soon as possible. Please be patient with me. Sorry for any inconvenience.
